exclude: |
    (?x)^(
        vendor/.*
    )$
repos:
-   repo: https://github.com/trinitronx/checkmake.git
    rev: 0.2.4
    hooks:
    - id: checkmake
      exclude: |
        (?x)^(
          vendor/.*|
          fixtures/missing_phony\.make
        )$
