name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:

  build:
    name: build and test
    runs-on: ubuntu-latest
    env:
      BUILDER_NAME: "GitHub Actions"
      BUILDER_EMAIL: noreply@actions.github.com

    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
      id: go

    - name: install dependencies
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
        sudo dpkg -i pandoc-2.7.3-1-amd64.deb

    - name: build and run unit tests
      run: make clean all test

    - name: Run checkmake on Makefile
      run: ./checkmake Makefile

